version: 0.4
name: 
  latency-rate-limited-1000_qps-memtier_benchmark-1Mkeys-load-string-with-200KiB-values
description: Runs memtier_benchmark, for a keyspace length of 1M keys loading STRINGs
  in which the value has a data size of 200K Bytes. Rate limited to 1000 ops/sec.
dbconfig:
  configuration-parameters:
    save: '""'
  check:
    keyspacelen: 0
  resources:
    requests:
      memory: 12g
tested-commands:
- set
redis-topologies:
- oss-standalone

build-variants:
- gcc:8.5.0-amd64-debian-buster-default
- dockerhub
clientconfig:
  run_image: redislabs/memtier_benchmark:edge
  tool: memtier_benchmark
  arguments: "\"--data-size\" \"200000\" --ratio 1:0 --key-pattern P:P --key-minimum=1
    --key-maximum 1000000 --test-time 180 -c 50 -t 4 --hide-histogram --rate-limiting
    5"
  resources:
    requests:
      cpus: '4'
      memory: 2g
  scalability:
    mode: '1:1'
    max_processes: 21

tested-groups:
- string
priority: 17
