version: 0.4
name: memtier_benchmark-1Mkeys-list-lpop-rpop-with-100B-values
description: Runs memtier_benchmark, for a keyspace length of 1M keys pre-loading
  LISTs in which the value has a data size of 100 Bytes. After pre-loading the data
  it issues LPOP and RPOP commands.
dbconfig:
  configuration-parameters:
    save: '""'
  check:
    keyspacelen: 1000000
  preload_tool:
    run_image: redislabs/memtier_benchmark:edge
    tool: memtier_benchmark
    arguments: '"--data-size" "100" --command "LPUSH __key__ __data__" --command-key-pattern="P"
      --key-minimum=1 --key-maximum 1000000 --test-time 60 -c 50 -t 4 --hide-histogram
      --pipeline 50'
  resources:
    requests:
      memory: 4g
  dataset_name: 1Mkeys-list-100B-size
  dataset_description: This dataset contains 1 million list keys, each with a data
    size of 100 bytes.
tested-groups:
- list
tested-commands:
- lpop
- rpop
redis-topologies:
- oss-standalone
build-variants:
- gcc:15.2.0-amd64-debian-bookworm-default
- gcc:15.2.0-arm64-debian-bookworm-default
- dockerhub
clientconfig:
  run_image: redislabs/memtier_benchmark:edge
  tool: memtier_benchmark
  arguments: '"--data-size" "100" --command "LPOP __key__" --command-key-pattern="R"
    --command "RPOP __key__" --command-key-pattern="R"  --key-minimum=1 --key-maximum
    1000000 --test-time 180 -c 50 -t 4 --hide-histogram'
  resources:
    requests:
      cpus: '4'
      memory: 2g
priority: 55
