version: 0.4
name: 
  latency-rate-limited-10000_qps-memtier_benchmark-1Mkeys-list-lpop-rpop-with-1KiB-values
description: Runs memtier_benchmark, for a keyspace length of 1M keys pre-loading
  LISTs in which the value has a data size of 1000 Bytes. After pre-loading the data
  it issues LPOP and RPOP commands. Rate limited to 10000 ops/sec.
dbconfig:
  configuration-parameters:
    save: '""'
  check:
    keyspacelen: 1000000
  preload_tool:
    run_image: redislabs/memtier_benchmark:2.1.0
    tool: memtier_benchmark
    arguments: '"--data-size" "1000" --command "LPUSH __key__ __data__" --command-key-pattern="P"
      --key-minimum=1 --key-maximum 1000000 --test-time 60 -c 50 -t 4 --hide-histogram'
  resources:
    requests:
      memory: 10g
tested-groups:
- list
tested-commands:
- lpop
- rpop
redis-topologies:
- oss-standalone
build-variants:
- gcc:8.5.0-amd64-debian-buster-default
- dockerhub
clientconfig:
  run_image: redislabs/memtier_benchmark:2.1.0
  tool: memtier_benchmark
  arguments: "\"--data-size\" \"1000\" --command \"LPOP __key__\" --command-key-pattern=\"\
    R\" --command \"RPOP __key__\" --command-key-pattern=\"R\"  --key-minimum=1 --key-maximum
    1000000 --test-time 180 -c 50 -t 4 --hide-histogram --rate-limiting 50"
  resources:
    requests:
      cpus: '4'
      memory: 2g

priority: 55
